package id.ac.ui.cs.advprog.order;

import id.ac.ui.cs.advprog.order.enums.CouponType;
import id.ac.ui.cs.advprog.order.model.Coupon;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

public class CouponTest {

    @Test
    void testCreateCoupon() {
        Coupon coupon = new Coupon(CouponType.FIXED, 10.0, 5, 1);
        coupon.setCode("FIXED-1");
        coupon.setStartDate(LocalDateTime.of(2025, 4, 10, 0, 0));
        coupon.setEndDate(LocalDateTime.of(2025, 5, 10, 0, 0));
        coupon.setDeletedAt(null);
        coupon.setCreatedAt(LocalDateTime.of(2025, 4, 1, 12, 0));
        coupon.setUpdatedAt(LocalDateTime.of(2025, 4, 5, 12, 0));
        coupon.setCreatedBy(UUID.randomUUID());

        assertEquals("FIXED-1", coupon.getCode());
        assertEquals(CouponType.FIXED, coupon.getCouponType());
        assertEquals(10.0, coupon.getDiscountAmount());
        assertEquals(5, coupon.getMaxUsage());
        assertEquals(0, coupon.getCurrentUsage());

        assertEquals(LocalDateTime.of(2025, 4, 10, 0, 0), coupon.getStartDate());
        assertEquals(LocalDateTime.of(2025, 5, 10, 0, 0), coupon.getEndDate());
        assertNull(coupon.getDeletedAt());
        assertEquals(LocalDateTime.of(2025, 4, 1, 12, 0), coupon.getCreatedAt());
        assertEquals(LocalDateTime.of(2025, 4, 5, 12, 0), coupon.getUpdatedAt());
        assertNotNull(coupon.getCreatedBy());
    }

    @Test
    void testIncrementUsage() {
        Coupon coupon = new Coupon(CouponType.PERCENTAGE, 15.0, 3, 2);
        coupon.incrementUsage();
        assertEquals(1, coupon.getCurrentUsage());
    }

    @Test
    void testIsValid() {
        Coupon coupon = new Coupon(CouponType.FIXED, 5.0, 2, 3);
        coupon.setStartDate(LocalDateTime.now().minusDays(1));
        coupon.setEndDate(LocalDateTime.now().plusDays(1));
        coupon.setDeletedAt(null);
        assertTrue(coupon.isValid());
    }

    @Test
    void testCodeAutoGeneratedFormat() {
        Coupon coupon1 = new Coupon(CouponType.FIXED, 10.0, 5, 1);
        Coupon coupon2 = new Coupon(CouponType.FIXED, 20.0, 5, 2);

        assertEquals("FIXED-1", coupon1.getCode());
        assertEquals("FIXED-2", coupon2.getCode());
    }




    @Test
    void testInvalidEnumParsing() {
        assertThrows(IllegalArgumentException.class, () -> {
            CouponType.valueOf("INVALID_ENUM");
        });
    }

    @Test
    void testCreateCouponWithNegativeValue() {
        Coupon coupon = new Coupon(CouponType.PERCENTAGE, -10.0, 3, 2);
        assertFalse(coupon.isValid());
    }

    @Test
    void testExceedMaxUsage() {
        Coupon coupon = new Coupon(CouponType.RANDOM, 10.0, 1, 2);
        coupon.incrementUsage();
        coupon.incrementUsage();
        assertFalse(coupon.isValid());
    }
    @Test
    void testCouponValidWithinDateRange() {
        Coupon coupon = new Coupon(CouponType.FIXED, 5.0, 3, 1);
        coupon.setStartDate(LocalDateTime.now().minusDays(1));
        coupon.setEndDate(LocalDateTime.now().plusDays(1));
        assertTrue(coupon.isValid());
    }

    @Test
    void testCouponInvalidIfBeforeStartDate() {
        Coupon coupon = new Coupon(CouponType.FIXED, 5.0, 3, 1);
        coupon.setStartDate(LocalDateTime.now().plusDays(1));
        coupon.setEndDate(LocalDateTime.now().plusDays(3));
        assertFalse(coupon.isValid());
    }

    @Test
    void testCouponInvalidIfAfterEndDate() {
        Coupon coupon = new Coupon(CouponType.FIXED, 5.0, 3, 1);
        coupon.setStartDate(LocalDateTime.now().minusDays(3));
        coupon.setEndDate(LocalDateTime.now().minusDays(1));
        assertFalse(coupon.isValid());
    }

    @Test
    void testCouponInvalidIfDeleted() {
        Coupon coupon = new Coupon(CouponType.FIXED, 5.0, 3, 1);
        coupon.setDeletedAt(LocalDateTime.now());
        assertFalse(coupon.isValid());
    }

    @Test
    void testCouponValidIfAllConditionsMet() {
        Coupon coupon = new Coupon(CouponType.FIXED, 5.0, 3, 1);
        coupon.setStartDate(LocalDateTime.now().minusDays(1));
        coupon.setEndDate(LocalDateTime.now().plusDays(1));
        coupon.setDeletedAt(null);
        assertTrue(coupon.isValid());
    }

    @Test
    void testAutomaticFieldsOnCreation() {
        Coupon coupon = new Coupon(CouponType.FIXED, 25.0, 10, 99);

        assertNotNull(coupon.getId(), "ID should be auto-generated");
        assertEquals("FIXED-1", coupon.getCode(), "Code should be auto-generated using type and index");
        assertEquals(0, coupon.getCurrentUsage(), "Current usage should be initialized to 0");
        assertNotNull(coupon.getCreatedAt(), "CreatedAt should be set on creation");
    }


}
